- 👋 Hi, I’m @Alex137614
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...

<!---10_7_8e87_5cd0_d9b3
Alex137614/Alex137614 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
10_7_8e87_5cd0_d9b3
